#!/bin/sh

. /lib/svc/share/smf_include.sh

# ----- *ADVANCED* CONFIGURATION -----
# Only change these options if you know what you are doing!
#
# The folder where Transmission stores the config & web files.
# ONLY change this you have it at a non-default location
#TRANSMISSION_HOME="/var/config/transmission-daemon"
#TRANSMISSION_WEB_HOME="/usr/local/share/"
#
# The arguments passed on to transmission-daemon.
# ONLY change this you need to, otherwise use the
# settings file as per above.
#TRANSMISSION_ARGS=""


# ----- END OF CONFIGURATION -----

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NAME=transmission-daemon
DAEMON=`which ${NAME}`

# Exit if the package is not installed
[ -x "${DAEMON}" ] || exit $SMF_EXIT_ERR_FATAL

#
# Function that starts the daemon/service
#

do_start()
{
	# Export the configuration/web directory, if set
	if [ -n "$TRANSMISSION_HOME" ]; then
		export TRANSMISSION_HOME
	fi
	if [ -n "$TRANSMISSION_WEB_HOME" ]; then
		export TRANSMISSION_WEB_HOME
	fi

	${DAEMON} ${TRANSMISSION_ARGS}
}

#
# Function that stops the daemon/service
#
do_stop()
{
	pkill -9 transmission
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	refresh)
		do_stop
		do_start
		;;
	*)
		echo "Usage: ${0} {start|stop|refresh}" >&2
		exit $SMF_EXIT_ERR_FATAL
		;;
esac

exit $SMF_EXIT_OK
